### ISSUE TITLE
Crash while checking crafting status over ME Network Bridge

### ISSUE THREAD

**Issue by JoJoDeveloping** [AppliedEnergistics/Applied-Energistics-2#2347]
I wanted to auto-craft something over the ME Network bridge, which did not work (the window closed itself). I then wanted to check what is being crafted. The "craftiong status window" showed up for a fractrion of a second and then MC crashed and told me that "A fatal error occurred, this connection is terminated".
Stack trace / Crash log:
http://pastebin.com/YtMLMSBw
Please keep in mind that the method in which the crash happened, "func_75142_b", is "detectAndSendChanges"
AE2 Version:  rv3-beta-6
Forge version: 1.7.10-10.13.4.1614 (latest)

**Comment by Rocker545** [comment]
I also have this problem

**Comment by Rocker545** [comment]
JoJoDeveloping does this happen to you in a rftools world?

**Comment by JoJoDeveloping** [comment]
No, in a galacticraft world. Btw it only happens occasionally, e.g. it works when using a wireless terminal (the extracells one), and if I use it first the bug does not occur when using a terminal.

**Comment by Rocker545** [comment]
Well it happened to me in an rftools dimension and I also can't autocraft anything from inside the rftools dimension

**Comment by JelmarG** [comment]
I had a similar problem, with the GUI closing when trying to auto-craft. But my client didn't crash. I narrowed it down to the method of chunkloading the QNB's. First I was loading them with FTBUtils (the chunk claiming/loading window thingy). After switching to chunkloader / spotloader (Chickenchunks), the problem seemed to have been fixed.

**Comment by mindforger** [comment]
Chickenchunks are no good solution, they tend to cause chunk unload/reload loops and half loaded chunks! switch to MFR Chunkloaders or Railcraft Chunkloaders, thrust me on that :)

or did he fixe those bugs recently (i mean in the past two weeks, since i know the latest version  still doing this funky stuff until then)

**Comment by Humsas** [comment]
I also had that problem. After lots of testing, finally found out, that if you have something in this inventory slot and try auto-craft, you receive this error.


![error](https://cloud.githubusercontent.com/assets/1152806/20192519/e2ab8650-a792-11e6-8eb6-4b181b4448c7.png)

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
