### ISSUE TITLE
Cant access my ME network when I´m offline

### ISSUE THREAD

**Issue by ToserBan** [AppliedEnergistics/Applied-Energistics-2#4225]
Hi,
Yesterday the mojang auth servers where down and I experienced a problem when i tried to put stuff in my ME system or pull something out or even tried to open the ME drives. All 3 things didnt work.
This happened in a single player world.

- Minecraft Version:1.12.2 
- AE2 Version: appliedenergistics2-rv6-stable-7.jar
- Forge Version: 14.23.5.2838

How to reproduce:
1. Build a ME system in your single player world
2. Stop playing, close minecraft completely
3. Unplug your ethernet cable from your computer
4. Start minecraft in offline mode
5. Try to put things into your ME system or pull things out.

After the mojang servers where up again I tried to use a security terminal with a biometric card, but as i understand it cannot be used for yourself but only to grant access to other players on MP worlds. I´m sure there is already a solution for that problem and I tried to find a solution in the internet but didnt find one. How can i use my ME system in offline mode ?

**Comment by ToserBan** [comment]
I tried a biometric card which is not bound to me and it worked. As far as i understand, if i would open this game for multiplayer and use an unbound biometric card, everyone can access the ME system ? Anyway, my problem is solved, maybe there are other ways to achieve this, lets say, if my internet would never come back ?

**Comment by yueh** [comment]
That is basically how minecraft itself works. When playing in offline mode, it is basically a completely different account compared to normally.

Basically it will work fine, when always used in online or offline mode. But switching between them is identical as logging into another account and playing with them. And there isn't really way to detect, that both profiles are actually the same player.

I haven't looked at the current launcher, but the old ones only needed to login every couple days. So as long as you'd logged into your account in the recent past, it would use the same profile.

Maybe that isn't the case anymore? But if so. Really no idea how to solve it.
For local use, the wildcard biometric card is certainly a good solution for now in case your internet might be unstable or unavailable for some time.

**Comment by ToserBan** [comment]
If the wildcard biometric card is the best solution for this problem, I´m happy with it. Thanks to made things clear about being offline is like logging in with a different account. I wasnt aware of that.

**Comment by yueh** [comment]
Or simply breaking the security terminal and replacing it as it will transfer the ownership to the other account. E.g. in case you forgot the wildcard. Both should be a good option for a single player world.

For servers it might be a bit different. But then again, if a server runs in offline mode, everyone can log into it under your account. So it would be pretty useless to have any protection.
