### ISSUE TITLE
After running my All the mods 10 server 1.21.1 for a hour or so tps is going down to a crawl fast....

### ISSUE THREAD

**Issue by jpeaglesandkatz** [AppliedEnergistics/Applied-Energistics-2#8329]
### How to reproduce the performance issue

I have no idea tbh... I've cleaned out a lot of garbage from my ae2 system. If you look at the ae2 thread in the spark profile it takes up most of the time... Even after removing most of the disks from the ae2 system, the tps stays the same.

Server is in house on my local LAN and running Debian 12... Client is running on Win 11.

### Spark profile link

https://spark.lucko.me/xbaJ7GE0s6

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

**Comment by Kevin-Marsh** [comment]
I am not sure but i think this might be your wireless terminal rather than your ae storage. What do you have in it or have enabled in it?

**Comment by Mari023** [comment]
It looks like both ae2 and ae2wtlib take a lot of time indexing the storage in your system.
I am not sure if I could maybe improve something on ae2wtlib's side, but given that ae2 also struggles indexing the system for it's own purposes, there is probably a more general problem with your network.

how many different items does your network store approximately?

**Comment by TheOnlyStink** [comment]
I have a similar issue, but it seems to present a little differently. It looks like one of the same threads is taking a long time to process - StorageService.UpdateCachedStacks(). The longer my server is up and running the further behind the ticks become. https://spark.lucko.me/G9VS5pm3lP

If you think this is a different issue, I'd be happy to open a different report.

**Comment by TheOnlyStink** [comment]
Yes, ATM10 version 2.23
grids.zip link:
https://drive.google.com/file/d/1ISVl6ZT6JlkMs9Mri-PjrJjVVGJGBxHn/view?usp=drive_link

**Comment by Technici4n** [comment]
Hi, can you make that link publicly accessible? Thanks

**Comment by TheOnlyStink** [comment]
My apologies, it should be shared globally now.

Thanks!

________________________________

**Comment by Technici4n** [comment]
Hi, this was fixed in v19.1.3-beta. Can you try it?

**Comment by TheOnlyStink** [comment]
Sure thing, just loaded it up on the server and I'll let it rip for a while.

**Comment by TheOnlyStink** [comment]
I've run the new version for the past couple of hours, even pumped soul surge through AE2 to my Hydroponics Beds to increase the number items going in and out of the system. No major degradation in performance like before. Thank you for looking into this! https://spark.lucko.me/oE5dkYExTH

**Comment by jpeaglesandkatz** [comment]
Appologies for not responding to the questions earlier.... Thank you all for the added feedback and questions..

After cleaning out my storage as much as I can etc.... Removing all export busses, disabling several addon mods, Troubleshooting everything I could the problem didn't resolve.. 
Yesterday I noticed the new beta for Ae2 and updated..  It seems the update to storageservice did indeed fix the problem.

Thanks a lot for the quick reponse and fix (fingers crossed).

This issue had me flabbergasted for weeks.

**Comment by Technici4n** [comment]
Amazing, thank you for your answers. :)
